program: McGovernChristian09.o getdouble.o
	 gcc McGovernChristian09.o getdouble.o -o program -lm

McGovernChristian09.o: McGovernChristian09.c getdouble.h 
		       gcc -c McGovernChristian09.c

getdouble.o: getdouble.c getdouble.h
	     gcc -c getdouble.c 
