program: McGovernChristian05.o getdouble.o
	gcc McGovernChristian05.o getdouble.o -o program -lm

McGovernChristian05.o: McGovernChristian05.c getdouble.h
	gcc -c McGovernChristian05.c 

getdouble.o: getdouble.c getdouble.h
	gcc -c getdouble.c 

